networks:
  wisecube-net:
    external: true
services:
  wisecube-api:
    depends_on:
    - wisecube-pythia
    - wisecube-postgres
    image: public.ecr.aws/u9o1b9m6/wisecube-graphql-api:latest
    networks:
    - wisecube-net
  wisecube-grafana:
    depends_on:
    - wisecube-postgres
    environment:
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    - GF_AUTH_BASIC_ENABLED=false
    - GF_AUTH_DISABLE_LOGIN_FORM=true
    - GF_AUTH_DISABLE_SIGNOUT_MENU=true
    - GF_SECURITY_ALLOW_EMBEDDING=true
    - GF_SERVER_SERVE_FROM_SUB_PATH=true
    - GF_SERVE_FROM_SUB_PATH=true
    - GF_AUTH_PROXY_ENABLED=true
    - GF_SERVER_DOMAIN=localhost
    - GF_SERVER_ROOT_URL=http://localhost:8000/grafana/
    image: grafana/grafana:8.3.4
    networks:
    - wisecube-net
    volumes:
    - ${PWD}/grafana/provisioning:/etc/grafana/provisioning
    - ${PWD}/grafana/dashboards:/var/lib/grafana/dashboards
  wisecube-kong-dbless:
    container_name: wisecube-kong-dbless
    environment:
    - KONG_DATABASE=off
    - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong_config.yml
    - KONG_PROXY_ACCESS_LOG=/dev/stdout
    - KONG_ADMIN_ACCESS_LOG=/dev/stdout
    - KONG_PROXY_ERROR_LOG=/dev/stderr
    - KONG_ADMIN_ERROR_LOG=/dev/stderr
    - KONG_ADMIN_LISTEN=0.0.0.0:8001
    - KONG_ADMIN_GUI_URL=http://localhost:8002
    image: kong/kong-gateway:3.6.1.2
    networks:
    - wisecube-net
    ports:
    - 8000:8000
    - 8443:8443
    - 8001:8001
    - 8444:8444
    - 8002:8002
    - 8445:8445
    - 8003:8003
    - 8004:8004
    volumes:
    - ${PWD}/kong:/kong/declarative/
  wisecube-postgres:
    environment:
      POSTGRES_DB: pythia
      POSTGRES_PASSWORD: wisecube2024
      POSTGRES_USER: wisecube
    image: postgres:latest
    networks:
    - wisecube-net
    volumes:
    - source: wisecube_postgres_data
      target: /var/lib/postgresql/data
      type: volume
  wisecube-pythia:
    environment:
    - OPENAI_API_KEY=sdadada
    image: public.ecr.aws/u9o1b9m6/wisecube-pythia:latest
    networks:
    - wisecube-net
version: '3.8'
volumes:
  wisecube_postgres_data:
    external: true
