apiVersion: 1

datasources:
  - name: postgres-datasource
    uid: pgds #THIS IS IMPORTANT ON THE DASHBOARD MUST BE THE SAME
    orgId: 1
    type: postgres
    url: wisecube-postgres:5432
    database: pythia
    user: wisecube
    basicAuth: false
    secureJsonData:
      password: wisecube2024
    jsonData:
      sslmode: disable
      tlsAuth: false
      tlsAuthWithCACert: false
      connMaxLifetime: 14400
      postgresVersion: 903
      timescaledb: false
    isDefault: true