{
 "title": "AccuracyByUser",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RequestDurationByUser",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT duration, date, user_id FROM wisecube_logs GROUP BY date, user_id, duration LIMIT 50 "
    }
   ]
  },
  {
   "title": "MaxAccuracyByUser",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT MAX(accuracy), user_id FROM metrics GROUP BY user_id LIMIT 50 "
    }
   ]
  },
  {
   "title": "AllQueries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT accuracy, contradiction, entailment, neutral, user_id, id FROM metrics GROUP BY id LIMIT 50 "
    }
   ]
  },
  {
   "title": "NeutralByUser",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT AVG(neutral), user_id FROM metrics GROUP BY user_id LIMIT 50 "
    }
   ]
  },
  {
   "title": "EntailmentByUser",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT AVG(entailment), user_id FROM metrics GROUP BY user_id LIMIT 50 "
    }
   ]
  },
  {
   "title": "ContradictionByUser",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT AVG(contradiction), user_id FROM metrics GROUP BY user_id LIMIT 50 "
    }
   ]
  },
  {
   "title": "Accuracy By user",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT AVG(accuracy), user_id FROM metrics GROUP BY user_id LIMIT 50 "
    }
   ]
  }
 ]
}