{
 "title": "PythiaQueries",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "UserNames",
    "query": "SELECT\n  user_id\nFROM\n  pythia_data\nGROUP BY\n  user_id\nLIMIT\n  50"
   },
   {
    "name": "Questions",
    "query": "SELECT\n  question\nFROM\n  pythia_data\nGROUP BY\n  question\nLIMIT\n  500"
   },
   {
    "name": "Classes",
    "query": "entailment,contradiction,neutral"
   }
  ]
 },
 "panels": [
  {
   "title": "CountOfQueryByUser",
   "type": "piechart",
   "gridPos": { "h": 19, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nuser_id,\n  COUNT(user_id)\n  \nFROM\n  pythia_data\nWHERE user_id IN ( $UserNames  )\nGROUP BY\n  user_id\n\nORDER BY\n  user_id ASC\n"
    }
   ]
  },
  {
   "title": "PythiaMetrics",
   "type": "table",
   "gridPos": { "h": 19, "w": 14, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT p.user_id , p.date, p.question, m.accuracy, m.contradiction, m.entailment, m.neutral FROM pythia_data as p JOIN metrics as m ON p.id = m.id WHERE p.user_id IN ($UserNames);"
    }
   ]
  },
  {
   "title": "Claims",
   "type": "table",
   "gridPos": { "h": 17, "w": 23, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT p.user_id , p.date, p.question, c.class, ARRAY_AGG(cc.claim) AS claims\nFROM pythia_data as p\nJOIN claims as c ON p.id = c.pythia_data_id\nJOIN claim_claim as cc ON cc.claim_id  = c.id\nWHERE p.user_id IN ($UserNames) AND p.question IN ( $Questions) AND c.class IN ( $Classes  )\nGROUP BY p.user_id, p.date, p.question, c.class\nORDER BY date desc \n\n\n"
    }
   ]
  },
  {
   "title": "ClaimsTriplesByQuestion",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT p.id as questionId, c.class, ARRAY_AGG(cc.claim) AS claims\nFROM pythia_data as p\nJOIN claims as c ON p.id = c.pythia_data_id\nJOIN claim_claim as cc ON cc.claim_id  = c.id\nWHERE p.user_id IN ($UserNames) AND p.question IN ( $Questions) AND c.class IN ( $Classes  )\nGROUP BY p.id, c.id, c.class\n\n\n"
    }
   ]
  }
 ]
}